# Generated by Django 2.2 on 2021-08-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0002_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
