# Generated by Django 2.2 on 2021-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0003_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/images/'),
        ),
    ]
