# Generated by Django 2.2 on 2021-09-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0006_auto_20210901_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
