# Generated by Django 2.2 on 2021-09-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0010_auto_20210903_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
