# Generated by Django 2.2 on 2021-08-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
